export const api = {
  login: '/api/login',
  loginOut: '/api/loginOut',
  userInfoMenu: '/api/getUserMenuList',
  menuList: '/api/sysMenu/',
  userAllList: '/api/getAllUser',
  getAllRole: '/api/getAllRole',
  sysMenutree: '/api/sysMenutree/',
  getRoleTreePer: '/api/getRoleTreePer/',
  setRoleTreePer: '/api/setRoleTreePer/',
  createRole: '/api/createRole',
  updateRole: '/api/updateRole',
  deleteRole: '/api/deleteRole',
  createUser: '/api/user/createUser',
  updateUser: '/api/user/updateUser',
  deleteUser: '/api/user/deleteUser',
  createMenu: '/api/menu/createMenu',
  updateMenu: '/api/menu/updatedMenu',
  deleteMenu: '/api/menu/deleteMenu',
  loginLogs: '/api/loginLogs/list'
}
