export const api = {
  login: '/api/login',
  loginOut: '/api/loginOut',
  userInfoMenu: '/api/getUserMenuList',
  menuList: '/api/menu/list/',
  userAllList: '/api/user/list',
  getAllRole: '/api/role/list',
  sysMenutree: '/api/menu/sysMenutree/',
  getRoleTreePer: '/api/role/getRoleTreePer/',
  setRoleTreePer: '/api/role/setRoleTreePer/',
  createRole: '/api/role/createRole',
  updateRole: '/api/role/updateRole',
  deleteRole: '/api/role/deleteRole',
  createUser: '/api/user/createUser',
  updateUser: '/api/user/updateUser',
  deleteUser: '/api/user/deleteUser',
  createMenu: '/api/menu/createMenu',
  updateMenu: '/api/menu/updatedMenu',
  deleteMenu: '/api/menu/deleteMenu',
  loginLogs: '/api/loginLogs/list',
  operationLos: '/api/operationLos/list',
  selectMenuList: '/api/menu/selectMenuList',
  uploadImage: '/api/single/uploadImage/',
  articleList: '/api/blogs/articleList',
  createArticle: '/api/blogs/createArticle',
  articleClassList: '/api/blogs/articleClassList',
  articleTagsList: '/api/blogs/articleTagsList'
}
